#config_version=6

 mode:
    start_events: ball_starting
    priority: 200

 shots:
      jets:
        switch: s_bumper1, s_bumper2 
      


 counters:
      lb_jets_count:
        count_events: jets_hit
        starting_count: 0
        count_complete_value: 10
        count_interval: 1
        direction: up
        persist_state: true
        events_when_complete: Super_Jets_Go
        debug: true
      lb_jets_resume:
        enable_events: mode_base_started{current_player.sj_active>0}
        count_events: jets_hit
        starting_count: 0
        count_complete_value: 5
        count_interval: 1
        direction: up
        persist_state: false
        events_when_complete: Super_Jets_Resume_Go
        debug: true
        reset_on_complete: true
      lb_rollover_complete_count:
        count_events: rollover_lanes2_complete
        events_when_hit: rollover_lanes2_done
        starting_count: 0
        count_complete_value: 40
        reset_on_complete: true
        direction: up
        persist_state: false

 event_player:
      Super_Jets_Go:
        start_mode_super_jets
      Super_Jets_Go_Again:
        start_mode_super_jets

 variable_player:
      # s_bumper1_active:
      #   score: 500 + (device.counters.lb_rollover_complete_count.value * 50000)
      # s_bumper2_active:
      #   score: 500 + (device.counters.lb_rollover_complete_count.value * 50000)
      
      
     
      mode_super_jets_started:
        sj_active:
          int: 1
          action: set

 show_player:
      mode_super_jets_setup_started{current_player.sj_active>0}:
        Super_Jets_on:
          show_tokens:
            lights: l_super_jets  
 

   
    
