#config_version=6

mode:
  code: mpf.modes.credits.code.credits.Credits
  priority: 1000010
  start_events: reset_complete
  game_mode: false
  stop_on_ball_end: false

slide_player:
  credits_added:
    credit_added_slide:
      expire: 2s
  not_enough_credits:
    not_enough_credits_slide:
      expire: 2s
  enabling_free_play:
    enabling_free_play_slide:
      expire: 2s
  enabling_credit_play:
    enabling_credit_play_slide:
      expire: 2s
  max_credits_reached:
    max_credits_reached_slide:
      expire: 2s
  player_added:
    player_added_slide:
      expire: 1s

#slides

slides:
  credit_added_slide:
    - type: text
      text: (machine|credits_string)
      font_size: 10
  not_enough_credits_slide:
    - type: text
      text: INSERT COINS | (machine|credits_string)
      font_size: 10
  enabling_free_play_slide:
    - type: text
      text: ENABLING FREE PLAY
      font_size: 10
  enabling_credit_play_slide:
    - type: text
      text: ENABLING CREDIT PLAY
      font_size: 10
    - type: text
      text: (machine|credits_string)
      font_size: 7
  max_credits_reached_slide:
    - type: text
      text: MAX CREDITS REACHED
      font_size: 10
  player_added_slide:
    - type: text
      text: PLAYER ADDED
      font_size: 10
       

# SOUNDS
sound_player:
  credits_added:
    cash_in:
      action: play
      loops: 0
  not_enough_credits:
    need_more_money:
      action: play
      loops: 0
  player_added:
    player_added_sound:
      action: play
      loops: 0